rudderlabs/airbyte

airbyte-integrations/connectors/source-intercom/source_intercom/source.py

This change is to address issue of fetching all records in initial sync even though start_date is set in the configured spec
Add a check when parsing response from intercom API to accept only records that are after the start_date in case when state is not present i.e start_date could be used as state
1. `x.java`
2. `y.python`
Expand the relevant checklist and delete the others. 
<details><summary> <strong> New Connector </strong></summary>
<p>
If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
</p>
</details>
<details><summary> <strong> Updating a connector </strong></summary>
<p>
If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
</p>
</details>
<details><summary> <strong> Connector …

Intercom: Use start_date as initial state when no state is present

---

airbyte-integrations/connectors/source-chargebee/source_chargebee/spec.json
airbyte-integrations/connectors/source-google-ads/source_google_ads/spec.json
airbyte-integrations/connectors/source-intercom/source_intercom/spec.json
airbyte-integrations/connectors/source-iterable/source_iterable/spec.json
airbyte-integrations/connectors/source-klaviyo/integration_tests/spec.json
airbyte-integrations/connectors/source-klaviyo/source_klaviyo/source.py

> Remove any airbyte doc reference in fields description for supported source ( chargebee, intercom, iterable, klaviyo, google_ads )
> [Ticket link](https://www.notion.so/rudderstacks/d8ea6e5cd7b2481db207d6b239676688?v=a417c150dc2f4f989102ba3fbb4986fc&p=088a5e5691f34ce3abc4e1a6fcbb5413)
> We need to rebuild and publish images for chargebee, intercom, iterable, klaviyo, google_ads and also update the image versions of each source in source-definiton options

remove airbyte docs reference

---

airbyte-integrations/connectors/source-iterable/source_iterable/iterable_streams.py

> According to Iterable [docs](https://support.iterable.com/hc/en-us/articles/360043464871-API-Keys-#using-api-keys) , API has changed the behavior of how it takes in API Key in the requests. Changed from query parameter to request header in form of `{”api-key”: ”the_api_key”}`. 
> [Ticket](https://www.notion.so/rudderstacks/d8ea6e5cd7b2481db207d6b239676688?v=a417c150dc2f4f989102ba3fbb4986fc&p=0b4d98cff7d44ba8a0e4ec0018e4bea6)
> I can't confirm that the issue is fixed, because the available API key works with both ways.

add api key in header

---

airbyte-integrations/connectors/source-recurly/source_recurly/schemas/invoices.json
airbyte-integrations/connectors/source-recurly/source_recurly/source.py
airbyte-integrations/connectors/source-recurly/source_recurly/spec.json

The config key name begin_time in the spec.json for recurly plays the same role as a start_date. Using begin_time is creating an error during running of the read task in the Airbyte container.
The state store in the sources db looks for start_date instead of begin_time. Therefore the key name has been changed to start_date for smooth integration

fix: modified recurly config key name

---

airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/spec.json

> Remove airbyte reference from field descriptions and set `additionalProperties` to false 
> [Notion Link](https://www.notion.so/rudderstacks/d8ea6e5cd7b2481db207d6b239676688?v=a417c150dc2f4f989102ba3fbb4986fc&p=63cf4fef966a46deba50cbc795b72801&pm=c)

Remove airbyte reference from field descriptions

---

airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py
airbyte-integrations/connectors/source-salesforce/source_salesforce/source.py

Adds custom primary key for
`PlatformEventUsageMetric`
`FormulaFunctionAllowedType`
---
Salesforce sends a field called `Id`, which Airbyte treats as the default primary key.
Id is not necessarily supposed to act as a primary key. As an example, for the above two resources, the Id field is the same for all the rows.
Since Id is the same and we treat whichever field Airbyte asks us to treat as pk, we send the same values under Id, and the warehouse dedupes the entire batch into 1 row, resulting in data loss.

fix: adds correct primary keys for salesforce resource

---

airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py

fix: exclude TaskWhoRelation from BULK API list
Squadcast Alert - https://app.squadcast.com/incident/636b0f92ae328f3139d90312
Add TaskWhoRelation to UNSUPPORTED_BULK_API_SALESFORCE_OBJECTS list
1. `x.java`
2. `y.python`

fix: exclude TaskWhoRelation from BULK API list

---

airbyte-integrations/connectors/source-amplitude/source_amplitude/spec.json
airbyte-integrations/connectors/source-freshdesk/source_freshdesk/spec.json

1. `x.java`
2. `y.python`
</details>
</details> …

Chore.spec cleanup

---

airbyte-integrations/connectors/source-intercom/source_intercom/source.py

Companies stream has a fallback if scroll API cannot be accessed.
While falling back, airbyte logs the message as an error, causing the termination of the task in RS.

fix: log type to warning for intercom scroll API

---

airbyte-integrations/connectors/source-stripe/source_stripe/streams.py

Add support for getting updates for incremental syncs for the following `stripe` resources using the event API
1. charges
2. customers
3. disputes
4. invoices
5. invoice_items
6. plans
7. products
8. subscriptions
9. transfers
> https://www.notion.so/rudderstacks/Stripe-updated-records-d1df062071b848cb87966c1b2d56f8a1
> https://www.notion.so/rudderstacks/Stripe-APIs-and-Correct-ETL-WIP-3914e964880e43cfa5e4e09535fa8e1a
> [Stripe: Add support for getting updated records](https://www.notion.so/rudderstacks/d8ea6e5cd7b2481db207d6b239676688?v=799e76e4eabd45b3ad80c87fdebdb765&p=2e0568e15419421c99d926677107cc27&pm=c)

feat: add support for updating records for stripe

---

airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/streams.py

We need to save states more frequently. We save the state only at the end of the sync process.
[ticket](https://www.notion.so/rudderstacks/Fix-Hubspot-Oauth-Role-to-singer-hubspot-8125c7f7972e435b9760a88399fd4a6e?pvs=4)

chore: make zendesk support connector to save state frequently

---

airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/streams.py

We need to move the checkpoint interval property to a supper class to allow all paginated zendesk streams to emit message events. Currently, we are can use the functionality for users and tickets streams but not for sla ratings.

fix: move checkpoint interval to supper class

---

airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/spec.json

Revert the additionalProperties to true as Airbyte has. It causes issues with the front end.

fix: allow additional properties in spec Zendesk support

---

airbyte-integrations/connectors/source-facebook-marketing/integration_tests/spec.json

1. `x.java`
2. `y.python`
</details>
</details> …

chore: cleanup spec for fb marketing

---

airbyte-integrations/connectors/source-klaviyo/source_klaviyo/streams.py

Converts events to something like this
Can see fields like `order`, `activity` etc are stringified so that they are not flattened.
https://www.notion.so/rudderstacks/Klaviyo-1600-columns-issue-d288b4f2cd8a4f73bf1850443a5627f5
1. `x.java`
2. `y.python`
</details>
If this is a community PR, the Airbyte engineer reviewing this PR is …

fix: fixes klaviyo events columns error

---

airbyte-integrations/connectors/source-intercom/source_intercom/manifest.yaml

https://www.notion.so/rudderstacks/Intercom-tags-data-issue-63f537333d844fc18e860f5e4fae948a?pvs=4
1. `x.java`
2. `y.python` …

fix: renames id field in tags records to tag_id

---

airbyte-integrations/connectors/source-stripe/source_stripe/streams.py

fix: rename record id to stripe id

---

airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py

fix: retry token expired errors hubspot

---

airbyte-integrations/connectors/source-klaviyo/source_klaviyo/streams.py

To reduce number of records being fetched by klaviyo events before syncing new data.
1. `x.java`
2. `y.python`
*If there are breaking changes, …

chore: reduces klaviyo lookback to 30mins

---

airbyte-integrations/connectors/source-mixpanel/source_mixpanel/streams/export.py

https://linear.app/rudderstack/issue/ETL-72/mixpanel-export-resource-issue
Renames event column to mixpanel_event to avoid collision with rudderstack reserved column name
1. `x.java`
2. `y.python`
*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3 …

fix: renames event to fix collision

---

airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py
airbyte-integrations/connectors/source-salesforce/source_salesforce/spec.yaml

1. Changed date format in latest image blocking source creation.
2. Some resources sync failing.
Issues detailed in comments here (https://linear.app/rudderstack/issue/ETL-55/salesforce-image-update)

fix: fixes salesforce connector errors

---

airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/streams.py

Ticket forms stores state in a different date format which is causing syncs to fail
Handled this format separately for this resource.
Before:
After:

fix: fixes ticket forms issue

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/source.py

fix: returns error message instead of exception object while validating account

ETL-114 fix.fb_ads_validation

---

airbyte-integrations/connectors/source-mixpanel/source_mixpanel/streams/export.py

https://linear.app/rudderstack/issue/ETL-123/add-primary-key-to-mixpanel-export-resource
Connector running fine after changes. Will test de-dup after deploying image on dev

feat: adds primary key to mixpanel export

---

airbyte-integrations/connectors/source-intercom/source_intercom/manifest.yaml

Primary key missing from catalog (https://linear.app/rudderstack/issue/ETL-135/add-primary-key-for-conversations-resource-intercom)

fix: adds primary key where missing

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/api.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/streams.py

feat: reset session in every sleep

---

airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py

Getting non json response from hubspot api because of which we are getting JsonDecodeError
Handles this case and adds retry to fix this.
Tried to simulate error by returning blank response in loop for first 2 runs. Code is retrying as expected here.

fix: fixes empty response from api

---

airbyte-integrations/connectors/source-google-ads/source_google_ads/custom_query_stream.py

* fix google ads custom query validation if segments.date already present in query

fix: google ads custom query validation

---

airbyte-integrations/connectors/source-stripe/source_stripe/streams.py

fix: updates query path to use record_id instead of id
updates query path to use record_id instead of id
1. `x.java`
2. `y.python`
*If there are breaking changes, please …

fix.stripe-customer-balance-transactions (ETL-261)

---

airbyte-integrations/connectors/source-shopify/source_shopify/source.py

* Handle api version being deprecated
* Update the api version to latest one

fix: update api version to 2023-07

---

airbyte-integrations/connectors/source-stripe/source_stripe/streams.py

To prevent syncs for customer balance transactions looking like stuck syncs and getting terminated.
https://linear.app/rudderstack/issue/ETL-280/add-additional-logs-for-customerbalancetransactions-stripe-to-avoid

chore: adds logs for periodic reporting of sync

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/api.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/source.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/spec.py

Add client_id and client_secret as config parameters for Facebook marketing connector. 
We will use client_sercet to hash the access token and add [app_secretproof](https://developers.facebook.com/docs/graph-api/securing-requests%20/). This may prevent access tokens from getting expired.  Blendo uses it and access tokens don't get expired.

feat.etl-304.addClientSecretInSpecs

---

airbyte-integrations/connectors/source-facebook-marketing/setup.py

We lock the cdk version for the Facebook connector to 67 as the state message format has changed in the newer version and we get empty states in the database. 
1. `x.java`
2. `y.python`
*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7 …

chore: lock cdk version for fb connector

---

airbyte-integrations/connectors/source-mixpanel/setup.py
airbyte-integrations/connectors/source-mixpanel/source_mixpanel/streams/export.py

We will try to parse the time field of the record. If we fail we will try the value _time and if we fail again we will emit the record. 
I have tested the connector locally . 
Aslo I have builder [v8.2.13-alpha.d285f01e6c](https://hub.docker.com/layers/rudderstack/source-mixpanel/v8.2.13-alpha.d285f01e6c/images/sha256-c18108d9ed734fd4deade9ec888f2153b33458c3da7fc40b5af085c5252ab0f5?context=repo) and tested the connector in rudder sources. States events are emitted as expected. 
1. `x.java`
2. `y.python`
*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for …

fix: try to parse record time

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/api.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/source.py
airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_insight_streams.py

fix: include internal error message

---

airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py

[ETL-336](https://linear.app/rudderstack/issue/ETL-336/the-allurion-hubspot-sync-is-failing-with-an-error-related-to-a)
Update give up handler:
-  to check exc.response is not None  and the check the `error.response.text` for the substring  `TOKEN_REFRESH_RETRIES_EXCEEDED_ERROR`
- to check the whole string of the error for the message `TOKEN_REFRESH_RETRIES_EXCEEDED_ERROR`
We get the error of the ticket when we get a connection Error with response value equal to None.
1. `x.java`
2. `y.python`
*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for …

fix: update hubspot giveup handler 

---

airbyte-integrations/connectors/source-zendesk-support/setup.py
airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/streams.py

[etl-302](https://linear.app/rudderstack/issue/ETL-302/migrate-zendesk-offset-pagination-resources)
Move the full refresh stream to cursor pagination.
Rename the offset pagination to time based pagination as we use the updated_at value to iterate over the rows. The API accepts the startAt value  and returns all the rows with updated at value greater than the start value 
[Time based pagination](https://linear.app/rudderstack/issue/ETL-302/migrate-zendesk-offset-pagination-resources)
1. `x.java`
2. `y.python`
*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for …

chore: use cursor base pagination for full refresh streams zender support

---

airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/streams.py

fix: ignore pagination for sla_policies and custom roles streams

---

airbyte-integrations/connectors/source-google-ads/setup.py
airbyte-integrations/connectors/source-google-ads/source_google_ads/google_ads.py
airbyte-integrations/connectors/source-google-ads/source_google_ads/source.py
airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py

chore: update google ads to use version v17

---

airbyte-integrations/connectors/source-recurly/setup.py
airbyte-integrations/connectors/source-recurly/source_recurly/streams.py

fix: add logic to slow down api calls to avoid rate limiting

---

airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/source.py

fix: Update Unsupported Fields For Facebook Connector
