rudderlabs/airbyte

- airbyte-integrations/connectors/source-iterable/source_iterable/source.py
1. `x.java`
2. `y.python`
Expand the relevant checklist and delete the others. 
<details><summary> <strong> New Connector </strong></summary>
<p>
If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
</p>
</details>
<details><summary> <strong> Updating a connector </strong></summary>
<p>
If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
</p>
</details>
<details><summary> <strong> Connector Generator </strong> </summary>
<p>
</p>
</details>
> Fix 'check' command failure when Iterable does not have any records in 'Lists' resource 

- airbyte-integrations/connectors/source-iterable/source_iterable/source.py
[Notion task](https://www.notion.so/rudderstacks/d8ea6e5cd7b2481db207d6b239676688?v=a417c150dc2f4f989102ba3fbb4986fc&p=5dbd469106384890a4532acc38fdd554)
> remove log from iterable connector

- airbyte-integrations/connectors/source-google-ads/source_google_ads/spec.json
- airbyte-integrations/connectors/source-intercom/source_intercom/spec.json
- airbyte-integrations/connectors/source-iterable/source_iterable/spec.json
- airbyte-integrations/connectors/source-klaviyo/integration_tests/spec.json
- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/source.py
Add official docs URLs
[Notion Ticket](https://www.notion.so/rudderstacks/d8ea6e5cd7b2481db207d6b239676688?v=a417c150dc2f4f989102ba3fbb4986fc&p=088a5e5691f34ce3abc4e1a6fcbb5413)
> add official doc links

- airbyte-integrations/connectors/source-google-ads/source_google_ads/spec.json
Made Destination table name mandatory in the GAQL query spec for google ads connector
Modified the spec.json in the google-ads connector
Expand the relevant checklist and delete the others. 
<details><summary> <strong> New Connector </strong></summary>
<p>
If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
</p>
</details>
<details><summary> <strong> Updating a connector </strong></summary>
<p>
If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
</p>
</details>
<details><summary> <strong> Connector Generator …
> added mandatory fields

- airbyte-integrations/connectors/source-google-ads/source_google_ads/spec.json
Table name cannot have capital letters or spaces or any other special characters, the syncs are failing otherwise
Added a message in the field description that the user cannot have capital letters or spaces or any special characters. And a regex validator with first character in small case and rest alpha numerics in small case.
None
Expand the relevant checklist and delete the others. 
<details><summary> <strong> New Connector </strong></summary>
<p>
If this is a community PR, the Airbyte engineer reviewing this PR is responsible for the below items. 
</p>
</details>
<details><summary> <strong> Updating a …
> modified table name description

- airbyte-integrations/connectors/source-hubspot/source_hubspot/spec.yaml
Change hubspot auth from dropdown to only oauth 2.0
</details>
</details>
</details>
<details><summary><strong>Unit</strong></summary>
*Put your unit tests output …
> Fix.hubspotAuthSpec

- airbyte-integrations/connectors/source-mixpanel/source_mixpanel/spec.json
- airbyte-integrations/connectors/source-mixpanel/source_mixpanel/streams/engage.py
Engage and Cohort Members are full sync resources, remove incremental property.
remove incremental property for engage stream
Fix sync for engage and cohort members
</details>
</details>
</details>
<details><summary><strong>Unit</strong></summary>
*Put your unit tests output here.*
</details>
<details><summary><strong>Integration</strong></summary> …
> fix: singer-mixpanel syncs for engage and cohort_members

- airbyte-integrations/connectors/source-zendesk-chat/source_zendesk_chat/schemas/conversions.json
- airbyte-integrations/connectors/source-zendesk-chat/source_zendesk_chat/schemas/department_events.json
- airbyte-integrations/connectors/source-zendesk-chat/source_zendesk_chat/source.py
- airbyte-integrations/connectors/source-zendesk-chat/source_zendesk_chat/streams.py
1. `x.java`
2. `y.python`
</details>
</details> …
> Feat.zendesk chat conversion department evets

- airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py
fix: singer-salesforce unsupported bulk api list updated
*added WorkOrderLineItemStatus and WorkOrderStatus to unsupported bulk api objects list*
</details>
</details>
</details> …
> fix: singer-salesforce unsupported bulk api list updated

- airbyte-integrations/connectors/source-amplitude/source_amplitude/api.py
Handling cases when sync is failing in amplitude when 0 data is present
1. `x.java`
2. `y.python`
</details>
</details>
</details> …
> fix: edge case handling in source amplitude

- airbyte-integrations/connectors/source-salesforce/setup.py
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: use version 1.0.79 of AirByteCDK

- airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py
1. `x.java`
2. `y.python`
</details>
</details> …
> feat(salesforce): add primary key for FormulaFunction

- airbyte-integrations/connectors/source-salesforce/setup.py
- airbyte-integrations/connectors/source-salesforce/source_salesforce/spec.yaml
Removing the description of the fields from the spec file.
1. `x.java`
2. `y.python`
</details>
</details>
</details> …
> fix.salesforceRemoveDescriptionFromSpec

- airbyte-integrations/connectors/source-hubspot/setup.py
- airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py
Insufficient scopes granted to campaigns resource.
Added required scopes for campaigns stream.
1. `x.java`
2. `y.python`
</details>
</details>
</details> …
> fix: hubspot scope issue

- airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py
https://www.notion.so/rudderstacks/Hubspot-sync-fails-due-to-token-expiration-c865d79e32b64a248cd5e88c3209c862
Fetching creds when we get oauth token expired error
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: 30 min token expire

- airbyte-integrations/connectors/source-hubspot/setup.py
- airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py
https://www.notion.so/rudderstacks/Airbyte-scope-definition-issue-for-Hubspot-resources-0e4274a78958481cadbb316199008617?d=a013037995bb4b4c97073590d5adeebb
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: hubspot scope

- airbyte-integrations/connectors/source-google-analytics-data-api/source_google_analytics_data_api/spec.json
Removing the description of the fields from the spec file.
1. `x.java`
2. `y.python`
</details>
</details>
</details> …
> chore.removeDescriptionFromSpecGAV4

- airbyte-integrations/connectors/source-google-search-console/source_google_search_console/spec.json
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: removes stale description from Google Search Console

- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/spec.py
Removing the description of the fields from the spec file.
1. `x.java`
2. `y.python`
</details>
</details>
</details> …
> feat.removeDescriptionFromSpecForFBMarketingConnector

- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/spec.py
move access token at the top specs
1. `x.java`
2. `y.python`
</details>
</details>
</details>
<details><summary><strong>Unit</strong></summary> …
> chore: move access token at the top

- airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py
Resource Names:
1. TabDefinition
2. AppDefinition
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: adds primary keys for Salesforce

- airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py
Resource Names: Publisher
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: adds primary keys for  Salesforce

- airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: overrides pk for ApexPageInfo

- airbyte-integrations/connectors/source-amplitude/source_amplitude/api.py
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: avoid name collision with Rudderstack userId

- airbyte-integrations/connectors/source-google-analytics-data-api/source_google_analytics_data_api/spec.json
Add examples for `date_ranges_start_date` for web app to choose the right date format.
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: add example values for start date ga v4 in spec file

- airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py
https://www.notion.so/rudderstacks/Hubspot-contacts-scope-deprecation-impact-32804d22d90d4232b8a4b23cbba56704
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: to handle contacts scope deprecation

- airbyte-integrations/connectors/source-google-ads/source_google_ads/spec.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py
chore: modifies descriptions in spec file
> fix: adds primary key for AccountPerformanceReport

- airbyte-integrations/connectors/source-bing-ads/source_bing_ads/spec.json
[removes descriptions from bing ads spec file](https://www.notion.so/rudderstacks/Cleanup-Spec-for-Bing-Ads-1427fa6ebc12479cb70060596646ad3e)
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: removes descriptions from bing ads spec file

- airbyte-integrations/connectors/source-iterable/source_iterable/streams.py
*(Iterable) Primary Key config for list users*
*Add email in the primary key config for list users resource in iterable*
1. `x.java`
2. `y.python`
> fix: add userId in list users primary key config for iterable source

- airbyte-integrations/connectors/source-google-ads/source_google_ads/spec.json
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: typo in google ads spec

- airbyte-integrations/connectors/source-bing-ads/source_bing_ads/spec.json
fix: removes format type for start_date for bing ads
1. `x.java`
2. `y.python`
</details>
</details>
</details> …
> fix: removes format type for start_date

- airbyte-integrations/connectors/source-sendgrid/source_sendgrid/spec.json
Update Sendgrid specs to use type integer only for start time. 
Airbyte supports both string and integer but this doesn't work for us as the UI can't handle both.
We choose type integer to maintain backward compatibility.
User integer as a type for start time.
1. `x.java`
2. `y.python`
</details>
If this is a community PR, the …
> chore: update start time in sendgrid specs

- .github/workflows/build-source-image.yaml
1. `x.java`
2. `y.python`
</details>
</details> …
> chore: new workflow file

- .github/workflows/build-source-image.yaml
[Notion Task](https://www.notion.so/rudderstacks/Development-Github-Actions-for-Building-Airbyte-Sources-435beef6a06e42c4a52d5a5d946fd4ea)
[Investigation Doc](https://www.notion.so/rudderstacks/Investigation-Github-Actions-For-Airbyte-Container-Build-Process-70e07c0a38c14aba8939c0d7b11f110b)
> feat: github action for building connectors

- .github/workflows/build-source-image.yaml
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: deprecated output format for GHA

- airbyte-integrations/connectors/source-google-analytics-v4/source_google_analytics_v4/spec.json
fix: cleanup spec for google analytics
1. `x.java`
2. `y.python`
</details>
</details>
</details> …
> fix: cleanup spec for google analytics

- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_streams.py
- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/streams.py
- capture warn.warnings and log them as normal warnings
- fix issues custom_canversion stream 
1. `x.java`
2. `y.python`
</details>
</details> …
> feat: update fb marketing connector t extract custom conversions

- airbyte-integrations/connectors/source-pipedrive/source_pipedrive/schemas/notes.json
- airbyte-integrations/connectors/source-pipedrive/source_pipedrive/schemas/product_fields.json
- airbyte-integrations/connectors/source-pipedrive/source_pipedrive/schemas/products.json
- airbyte-integrations/connectors/source-pipedrive/source_pipedrive/source.py
- airbyte-integrations/connectors/source-pipedrive/source_pipedrive/spec.json
- airbyte-integrations/connectors/source-pipedrive/source_pipedrive/streams.py
- clean specs to use only an API key
- small fix to the check command
- extra streams:
- notes
- products
- product fields 
1. `x.java`
2. `y.python`
</details>
</details> …
> chore: singer pipedrive

- .github/workflows/build-source-image.yaml
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: removes na option

- .github/workflows/build-source-image.yaml
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: typo while getting the last commit

- airbyte-integrations/connectors/source-pipedrive/source_pipedrive/spec.json
1. `x.java`
2. `y.python`
</details>
</details> …
> chore: reorder pipedrive settings

- airbyte-integrations/connectors/source-mixpanel/source_mixpanel/spec.json
1. `x.java`
2. `y.python`
</details>
</details> …
> chore: cleans mixpanel spec

- airbyte-integrations/connectors/source-mixpanel/source_mixpanel/spec.json
1. `x.java`
2. `y.python`
</details>
</details> …
> chore: cleans spec

- airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
1. `x.java`
2. `y.python`
</details>
</details> …
> chore: small fixes to stripe sub resources

- airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
*Fix for `no record_id specified in event` we used to delete the primary key because we dont need deduplication instead but it fails in rudder-sources. Instead deleting the primary key, replace it with uuid*
*Also fix the completed state in case of multiple slices*
> fix: stripe record_id missing and

- airbyte-integrations/connectors/source-stripe/source_stripe/spec.yaml
1. `x.java`
2. `y.python`
</details>
</details> …
> chore: cleans stripe spec

- airbyte-config/init/src/main/resources/seed/source_definitions.yaml
- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-shopify/Dockerfile
- airbyte-integrations/connectors/source-shopify/setup.py
- airbyte-integrations/connectors/source-shopify/source_shopify/source.py
- docs/integrations/sources/shopify.md
https://www.notion.so/rudderstacks/Shopify-OOM-issue-445e5e05605749b2898dfe851a4f4bc7?pvs=4
1. `x.java`
2. `y.python`
</details>
</details> …
> 🐛 Source Shopify: fix OOM/memory leak (#23473)

- airbyte-integrations/connectors/source-shopify/source_shopify/spec.json
To build image from main branch instead of feature branch so that it is easier to maintain and not miss any changes. We can always retrieve whatever we deleted (in this case oauth) from upstream.
1. `x.java`
2. `y.python`
</details>
If this is a community PR, the Airbyte engineer reviewing this PR is …
> chore: cleans shopify

- airbyte-integrations/connectors/source-shopify/source_shopify/spec.json
Removes dropdown from spec
1. `x.java`
2. `y.python`
</details>
</details>
</details>
<details><summary><strong>Unit</strong></summary>
*Put …
> chore: fixes minor issues in spec

- airbyte-integrations/connectors/source-shopify/source_shopify/spec.json
1. `x.java`
2. `y.python`
</details>
</details> …
> chore: adds desc for shopify name

- airbyte-integrations/connectors/source-hubspot/source_hubspot/source.py
- airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py
Adds retries with backoff while fetching scopes
> fix: hubspot dict issue

- airbyte-integrations/connectors/source-shopify/source_shopify/source.py
Fixes check call to shopify getting stuck retrying in specific cases.
https://www.notion.so/rudderstacks/Shopify-invalid-store-name-issue-9395d8a396b94ede8c73413d80f7fab2?pvs=4
Changes way for validating creds.
1. `x.java`
2. `y.python`
</details>
If this is a community PR, the Airbyte engineer reviewing this PR is responsible for …
> fix: fixes shopify name issue

- airbyte-integrations/connectors/source-amplitude/Dockerfile
1. `x.java`
2. `y.python`
</details>
</details> …
> chore: fixes missed conflict resolution

- airbyte-config/init/src/main/resources/seed/source_definitions.yaml
- airbyte-config/init/src/main/resources/seed/source_specs.yaml
- airbyte-integrations/connectors/source-amplitude/integration_tests/acceptance.py
- airbyte-integrations/connectors/source-amplitude/source_amplitude/spec.json
1. `x.java`
2. `y.python`
</details>
</details> …
> chore: fixes missed conflict in spec

- airbyte-integrations/connectors/source-shopify/source_shopify/source.py
Add logic to retry getting the shopify access scopes if we get a `NewConnectionError`
[ticket](https://www.notion.so/rudderstacks/Retry-Getting-access-scopes-for-shopify-connector-207f711f26f941dd9f16a0695c68a5a5?pvs=4)
1. `x.java`
2. `y.python`
</details>
If this is a community PR, the Airbyte engineer …
> fix: retry retrieving access scopes for shopify

- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/streams.py
https://www.notion.so/rudderstacks/Klaviyo-State-Storage-Issue-3c309eb4e5de45fd9a71caa76b5b757e?pvs=4
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: makes state emit more often

- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/spec.py
- airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py
- airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: resolves conflicts from upstream merge

- airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
https://www.notion.so/rudderstacks/Stripe-Image-update-dd82d2d7ec2f4f6599a1d3ef5384044c?pvs=4
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: adds api version in stripe request header

- airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: adds missing datetime import

- airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
1. `x.java`
2. `y.python`
</details>
</details> …
> fix: fixes datetime import

- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/spec.py
> fix: missing imports for FB marketing

- airbyte-integrations/connectors/source-stripe/source_stripe/source.py
- airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
> fix: stripe connector after merging airbyte changes

- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/streams.py
> chore: increase look back to 120 minutes for events steams of klaviyo

- airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
This reverts commit 68b82bdd1eeda0e72bfc5f559ce06cee8bf4f4c8.
1. `x.java`
2. `y.python`
*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rC …
> chore: revert rename record id to stripe id

- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/streams.py
> chore: save last next token for klaviyo stream

- airbyte-integrations/connectors/source-mixpanel/source_mixpanel/spec.json
- airbyte-integrations/connectors/source-mixpanel/source_mixpanel/streams/export.py
https://linear.app/rudderstack/issue/ETL-72#comment-ba308c78 (New image date format is blocking source creation)
1. `x.java`
2. `y.python`
*If there are breaking changes, …
> fix: fixes issue blocking source creation

- airbyte-integrations/connectors/source-mixpanel/source_mixpanel/source.py
Airbyte made a change in logic of getting resources for discover call recently. They 1st try to fetch some data from each resource and if this step is successful they are saying this stream is supported by source. This is to avoid issues where some api’s are not available due to pricing plans
Because of this logic this step (discover) is taking more time and causing some timeouts
https://linear.app/rudderstack/issue/ETL-82#comment-4830b5f9
Tested locally and observed discover calls are much faster now.
> fix: fixes discover taking too long

- airbyte-integrations/connectors/source-mixpanel/source_mixpanel/streams/export.py
Adds state checkpoint interval to export resource
https://linear.app/rudderstack/issue/ETL-81#comment-72ca682e
> fix: adds state_checkpoint_interval to export

- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/source.py
> ETL-114 fix: catch airbytetracedexception

- airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py
https://linear.app/rudderstack/issue/ETL-124/fix-primary-key-of-deal-pipelines-resource
Sync running fine when running connector directly. Will test end to end flow in dev
> fix: fixes deal_pipelines primary key

- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/spec.py
- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/base_streams.py
> chore: set page size to 500

- airbyte-integrations/connectors/source-intercom/Dockerfile
- airbyte-integrations/connectors/source-intercom/acceptance-test-config.yml
- airbyte-integrations/connectors/source-intercom/metadata.yaml
- airbyte-integrations/connectors/source-intercom/setup.py
- airbyte-integrations/connectors/source-intercom/source_intercom/components.py
- airbyte-integrations/connectors/source-intercom/source_intercom/manifest.yaml
- airbyte-integrations/connectors/source-intercom/source_intercom/schemas/admins.json
- airbyte-integrations/connectors/source-intercom/source_intercom/schemas/company_attributes.json
- airbyte-integrations/connectors/source-intercom/source_intercom/schemas/contact_attributes.json
- airbyte-integrations/connectors/source-intercom/source_intercom/schemas/contacts.json
- airbyte-integrations/connectors/source-intercom/source_intercom/schemas/conversations.json
- airbyte-integrations/connectors/source-intercom/source_intercom/spec.json
- docs/integrations/sources/intercom.md
Was getting some errors when building intercom image. Something might have been changed in cdk. So cherry picked the recent commit on upstream to update cdk version. **License for intercom is still MIT so there should be no issue.**
Cherry picked `34e7144` commit from https://github.com/airbytehq/airbyte/pull/29598
Image build succeeding now
> Source Intercom: migrate to latest cdk (0.50.2) (#29598)

- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/ad_account.json
- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/spec.py
> chore: set maximum value for max_batch_size

- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/api.py
- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/streams.py
> Chore.etl 77 handle requests connection reset

- airbyte-integrations/connectors/source-google-ads/source_google_ads/source.py
> fix(google-ads): handle unexpected errors during validation

- airbyte-integrations/connectors/source-stripe/integration_tests/configured_catalog.json
- airbyte-integrations/connectors/source-stripe/integration_tests/connected_account_configured_catalog.json
- airbyte-integrations/connectors/source-stripe/source_stripe/source.py
- airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
> fix: check for last slice

- airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py
Fixes syncs failing due to oauth token expiring mid sync
https://linear.app/rudderstack/issue/ETL-260/hubspot-source-syncs-failing-with-the-oauth-token-used-to-make-this
> fix: fixes oauth token expired error

- airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py
- airbyte-integrations/connectors/source-salesforce/source_salesforce/streams.py
Fixes some failing resources syncs in latest airbyte code of salesforce and re-enables some resources
https://linear.app/rudderstack/issue/ETL-258/happier-living-reported-getting-error-when-to-create-salesforce-as-a
> fix: salesforce fixes

- airbyte-integrations/connectors/source-google-ads/setup.py
- airbyte-integrations/connectors/source-google-ads/source_google_ads/custom_query_stream.py
- airbyte-integrations/connectors/source-google-ads/source_google_ads/google_ads.py
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/ad_group_ad_labels.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/ad_group_ad_report.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/ad_group_ads.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/ad_group_labels.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/ad_groups.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/campaign_labels.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/campaigns.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/click_view.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/display_keyword_performance_report.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/display_topics_performance_report.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/geographic_report.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/keyword_report.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/shopping_performance_report.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/user_location_report.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/source.py
- airbyte-integrations/connectors/source-google-ads/source_google_ads/spec.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py
*Google ads syncs failing as api version v13 is deprecated*
*update google-ads api version to v15*
> update google-ads api version to v15

- airbyte-integrations/connectors/source-facebook-marketing/setup.py
*update fb marketing api version to v18.0*
*update fb marketing sdk version to 18.0.5*
1. `x.java`
2. `y.python`
*If there are breaking changes, please merge this PR with …
> Chore.update fb marketing api version to v18.0 (ETL-270)

- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/api.py
Fixes the issue of fb ads syncs never completing due to being stuck waiting for rate limit to reset.
https://linear.app/rudderstack/issue/ETL-277/fb-ads-connector-stuck-retrying-endlessly
Details in task
> fix: adds max sleep time for fb ads

- airbyte-integrations/connectors/source-google-ads/setup.py
- airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py
> fix: update primary key of campaigns stream for Google_Ads connector

- airbyte-integrations/connectors/source-intercom/setup.py
- airbyte-integrations/connectors/source-intercom/source_intercom/manifest.yaml
We will ignore any 404 error for a conversation not found for conversation parts.
[ticket](https://linear.app/rudderstack/issue/ETL-273/conversation-parts-sync-failed-with-status-code-404-and-error-message)
1. `x.java`
2. `y.python`
*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release …
> fix: ignore 404 conversation not found for conversation parts stream

- airbyte-integrations/connectors/source-hubspot/source_hubspot/streams.py
Add this error message in the list of errors that we need to refresh the access token
`This oauth-token (COfahOr) is not valid for this request`
1. `x.java`
2. `y.python`
*For connector PRs, use this section to explain which type of semantic versioning bump occurs as a result of the changes. Refer to our [Semantic Versioning for Connectors](https://docs.airbyte.com/contributing-to-airbyte/#semantic-versioning-for-connectors) guidelines for more information. **Breaking changes to connectors must be documented by an Airbyte engineer (PR author, or reviewer for community PRs) by using the [Breaking Change Release Playbook](https://docs.google.com/document/d/1VYQggHbL_PN0dDDu7rCyzBLGRtX-R3cp …
> chore: update token expired error list

- airbyte-integrations/connectors/source-hubspot/setup.py
> chore: set cdk version for hubspot connector

- airbyte-integrations/connectors/source-stripe/setup.py
- airbyte-integrations/connectors/source-stripe/source_stripe/schemas/charges.json
- airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
Adding extra charges event types to capture all events related to changes.
1. `x.java`
2. `y.python`
*If there are breaking changes, please merge …
> fix: update charges steam with extra event types

- airbyte-integrations/connectors/source-klaviyo/setup.py
- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/schemas/campaigns.json
- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/schemas/email_templates.json
- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/schemas/events.json
- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/schemas/flows.json
- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/schemas/global_exclusions.json
- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/schemas/lists.json
- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/schemas/metrics.json
- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/schemas/segments.json
- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/schemas/segments_profiles.json
- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/source.py
- airbyte-integrations/connectors/source-klaviyo/source_klaviyo/streams.py
> feat: use latest api version for klaviyo

- airbyte-integrations/connectors/source-google-search-console/setup.py
- airbyte-integrations/connectors/source-google-search-console/source_google_search_console/spec.json
> fix: update google search console to latest image

- airbyte-integrations/connectors/source-shopify/setup.py
- airbyte-integrations/connectors/source-shopify/source_shopify/shopify_schema.py
- airbyte-integrations/connectors/source-shopify/source_shopify/source.py
> chore: update shopify version to 2024-07

- airbyte-integrations/connectors/source-stripe/source_stripe/streams.py
> chore: update stripe api version to 2024-06-20

- airbyte-integrations/connectors/source-zendesk-chat/setup.py
- airbyte-integrations/connectors/source-zendesk-chat/source_zendesk_chat/source.py
- airbyte-integrations/connectors/source-zendesk-chat/source_zendesk_chat/spec.json
- airbyte-integrations/connectors/source-zendesk-chat/source_zendesk_chat/streams.py
> chore: use subdomain in the base url for zendesk chat api. Also, the subdomain will be a required field

- airbyte-integrations/connectors/source-zendesk-support/source_zendesk_support/streams.py
> fix: remove page_size query param for user setting stream of zendesk support connector

- airbyte-integrations/connectors/source-facebook-marketing/setup.py
- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/api.py
- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/streams/streams.py
> chore: update fb-business dependency to v21.0.5

- airbyte-integrations/connectors/source-salesforce/source_salesforce/api.py
> chore: use rest api for case stream

- .github/workflows/build-source-image.yaml
> chore: use git commit shas in build source action

- .github/workflows/build-source-image.yaml
- airbyte-integrations/connectors/source-google-ads/setup.py
- airbyte-integrations/connectors/source-google-ads/source_google_ads/google_ads.py
- airbyte-integrations/connectors/source-google-ads/source_google_ads/schemas/campaigns.json
- airbyte-integrations/connectors/source-google-ads/source_google_ads/source.py
- airbyte-integrations/connectors/source-google-ads/source_google_ads/streams.py
> chore: update google ads to use version v19

- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/api.py
- airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/source.py
> fix: add the right access token for the debug_token call

- .github/workflows/connector_checklist.yml
- .github/workflows/label-github-issues-by-path.yml
- .github/workflows/label-prs-by-context.yml
> chore: add permissions section for github workflow
